vscode:
  extensions:
    - formulahendry.code-runner@0.9.14:U0vUPTCchGiTYlRHpW9ljQ==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==